#!/usr/bin/env ksh

[ ! -z $BASH_VERSION ] && gLogCommand="echo -e" || gLogCommand="print"

gLevDebug=4
gLevInfo=3
gLevWarn=2
gLevErr=1
gLevFail=0

gLevNames[$gLevDebug]=DEBUG
gLevNames[$gLevInfo]=INFO
gLevNames[$gLevWarn]=WARN
gLevNames[$gLevErr]=ERROR
gLevNames[$gLevFail]=FAIL

gLogInit=0
gLogDebug=

gColorRed=31
gColorGreen=32
gColorYellow=33
gColorPurple=35
gColorWhite=37

logReset() {
	gLogInit=0
	gLevLog=$gLevInfo
	unset gColors
	unset gLogFile
	unset gLogAppend
}

logStatus() {
	logDebug "gLogInit=$gLogInit, gColors=$gColors, gLevLog=${gLevNames[$gLevLog]}, gLogFile=$gLogFile, gLogAppend=$gLogAppend" 
}

logInit() {
	if [ $gLogDebug ]; then set -vx; fi
	if [ -f "$1" ]; then
		# Color property for log
		grep -i '^LOG4U\.LOGCOLORS' $1 >/dev/null 2>&1
		[ $? -eq 0 ] && gColors=1 || gColors=0

		# Logging level property
		lLevLogName=$(grep -i '^LOG4U\.LEVEL' $1 | cut -d '=' -f2)
		case $lLevLogName in
			"${gLevNames[$gLevDebug]}")
				gLevLog=$gLevDebug
				;;
			"${gLevNames[$gLevInfo]}")
				gLevLog=$gLevInfo
				;;
			"${gLevNames[$gLevWarn]}")
				gLevLog=$gLevWarn
				;;
			"${gLevNames[$gLevErr]}")
				gLevLog=$gLevErr
				;;
			"${gLevNames[$gLevFail]}")
				gLevLog=$gLevFail
				;;
			*)
				gLevLog=$gLevInfo
				logErr "Invalid property value for property LOG4U.LOGLEVEL. Defaulting to INFO level"
				;;
		esac
	
		# File logging property
		grep -i '^LOG4U\.LOGFILE' $1 >/dev/null 2>&1
		if [ $? -eq 0 ]; then
			# Property is defined
			lLogFile=$(grep -i '^LOG4U\.LOGFILE' $1 | cut -d '=' -f2 | cut -d ',' -f1)
			lLogAppend=$(grep -i '^LOG4U\.LOGFILE.*,.*$' $1 | cut -d '=' -f2 | cut -d ',' -f2)
			if [ ! -z "$lLogFile" ]; then
				gLogFile=$lLogFile
				case $lLogAppend in
					[ad])
						gLogAppend=$lLogAppend
						;;
					*)
						gLogAppend=a
						;;
				esac
			else
				gLogFile=""
				gLogAppend=""
			fi
		fi
		if [ -f "$gLogFile" -a "$gLogAppend" == "d" ]; then
			rm -f "$gLogFile"
		fi
	
		gLogInit=1
	else
		logFail "Failure initializing log4u. Config file $1 not found. Using default values for properties"
		logReset
	fi
	if [ $gLogDebug ]; then set +vx; fi
}

log() {
	if [ $gLogDebug ]; then set -vx; fi
	lBuf="$1"
	lLevCurr=$2
	lColor=$3
	lTm=$(date +"%d/%m/%Y %H:%M:%S")
	if [ ${gLevLog:-$gLevInfo} -ge $lLevCurr ]; then
		if [ ${gColors:-0} -eq 1 ]; then
			lMsg="\033[${lColor}m${lTm} - ${gLevNames[$lLevCurr]} - $0: $lBuf\033[37m"
		else
			lMsg="${lTm} - ${gLevNames[$lLevCurr]} - $0: $lBuf"
		fi

		if [ ! -z "$gLogFile" ]; then
			$gLogCommand "$lMsg" | tee -a $gLogFile
		else
			$gLogCommand "$lMsg"
		fi
	fi
	if [ $gLogDebug ]; then set +vx; fi
}

logDebug() {
	log "$1" $gLevDebug $gColorWhite
}

logInfo() {
	log "$1" $gLevInfo $gColorWhite
}

logWarn() {
	log "$1" $gLevWarn $gColorYellow
}

logErr() {
	log "$1" $gLevErr $gColorRed
}

logFail() {
	log "$1" $gLevFail $gColorPurple
}
